server :
  port : 8095
  tomcat:
    uri-encoding: UTF-8

spring:
  elasticsearch:
    rest:
      uris: ${ElasticSearchURL:192.168.3.13:9200}

# 信息安全
security:
  sql:
    enabled: true   # false表示关闭，true为打开，默认打开
    excludes:
      - /sakura/es        #忽略检查的url