#下面的是例子中的表
CREATE TABLE IF NOT EXISTS `project_manage`  (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `group_id` bigint(20) NULL DEFAULT NULL COMMENT '项目分组id，关联project_group分组表',
  `type_id` bigint(20) NULL DEFAULT NULL COMMENT '项目类型id，关联project_sys_dictonary字典表主键id',
  `project_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '项目名称',
  `project_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '项目编号',
  `contract_sign_time` datetime(0) NULL DEFAULT NULL COMMENT '合同签订时间',
  `contract_rule_final_accept_time` datetime(0) NULL DEFAULT NULL COMMENT '合同规定终验时间',
  `start_time` datetime(0) NULL DEFAULT NULL COMMENT '开工时间',
  `start_work_model_id` tinyint(1) UNSIGNED NULL DEFAULT 0 COMMENT '开工模式，0：无合同，1：有合同',
  `contract_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '合同编号',
  `customer_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '客户名称',
  `channel_source_id` bigint(255) NULL DEFAULT NULL COMMENT '渠道来源id，关联project_sys_dictonary字典表主键id',
  `sale_department` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '销售部门',
  `product_line_id` bigint(255) NULL DEFAULT NULL COMMENT '产品线id，关联project_sys_dictonary字典表主键id',
  `contract_amount` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '合同额',
  `contract_amount_prod` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '合同额-产品',
  `contract_amount_gather` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '合同额-集成',
  `contract_amount_service` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '合同额-服务',
  `project_backgroud` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '项目背景',
  `project_desc` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '项目范围（内容描述）',
  `project_needs` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '项目需求：（标书/合同）',
  `project_status` tinyint(1) NULL DEFAULT 0 COMMENT '项目状态，0正常，1停用',
  `project_risk` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '项目风险',
  `create_user_id` bigint(20) NULL DEFAULT NULL,
  `create_time` datetime(0) NULL DEFAULT NULL,
  `update_user_id` bigint(20) NULL DEFAULT NULL,
  `update_time` datetime(0) NULL DEFAULT NULL,
  `deleted` tinyint(2) NULL DEFAULT 0 COMMENT '是否删除（1：已删除，0：未删除）',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci COMMENT = '项目表' ROW_FORMAT = Dynamic;