#########################################################################################################
########################################## 文件上传 #############################################
######################################################################################
spring:
  servlet:
    multipart:
      max-file-size: 100MB # 最大支持文件大小
      max-request-size: 100MB # 最大支持请求大小

#########################################################################################################
########################################## minio #############################################
######################################################################################
minio:
  endpoint: http://216.240.130.167:9000
  accessKey: username
  secretKey: password



