server :
  port : 8083
  tomcat:
    uri-encoding: UTF-8

#########################################################################################################
########################################## 文件上传 #############################################
######################################################################################
spring:
  servlet:
    multipart:
      max-file-size: 100MB # 最大支持文件大小
      max-request-size: 100MB # 最大支持请求大小

#########################################################################################################
########################################## minio #############################################
######################################################################################
minio:
  endpoint: http://192.168.3.13:9000
  accessKey: username
  secretKey: password



