####################################################################################
###################################DataSource Config################################
####################################################################################
spring:
  datasource:
    # JDBC 配置
    type: com.alibaba.druid.pool.DruidDataSource
    #    schema:
    #      - classpath:/db/schema-mysql.sql
    #    data:
    #      - classpath:/db/data-mysql.sql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.130:3306/sakura?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
    druid:
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      validation-query: SELECT 'x' from dual
      validation-query-timeout: 30000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 300000
      filters: stat
      # 监控配置
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true  #是否启用StatFilter默认值true
        url-pattern: /druid/*
        #        exclusions: *.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
        session-stat-enable: true
        session-stat-max-count: 10
        principal-session-name:
        principal-cookie-name:
        profile-enable: true
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true #是否启用StatViewServlet默认值true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: admin
        allow:
        deny:
      # Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
      # 如果spring.datasource.druid.aop-patterns要代理的类没有定义interface请设置spring.aop.proxy-target-class=true
      #aop-patterns: #Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
#########################################################################################################
##########################################spring boot rabbitmq #############################################
#########################################################################################################
  rabbitmq:
    host: 192.168.1.130
    port: 5672
    virtual-host: /mall
    username: admin
    password: admin
    listener:
      simple:
        acknowledge-mode: manual #开启手动Ack。消息默认设置为自动ack，这种情况下，MQ只要确认消息发送成功，无须等待应答就会丢弃消息
        prefetch: 2

#########################################################################################################
##########################################spring boot redis #############################################
######################################################################################
  redis:
    database: 0           # Redis数据库索引（默认为0）
    host: 192.168.1.130   # Redis服务器地址
    port: 16379            # Redis服务器连接端口
    password:             #Redis服务器连接密码（默认为空）
    timeout: 5000ms            # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-idle: 8         # 连接池中的最大空闲连接
        min-idle: 1         # 连接池中的最小空闲连接
        max-active: 8       # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms        # 连接池最大阻塞等待时间（使用负值表示没有限制）
  profiles:
    active: dev

#########################################################################################################
########################################## 文件上传 #############################################
######################################################################################
  servlet:
    multipart:
      max-file-size: 100MB # 最大支持文件大小
      max-request-size: 100MB # 最大支持请求大小

#########################################################################################################
########################################## flyway #############################################
######################################################################################
  flyway:
    enabled: true
    # 迁移前校验 SQL 文件是否存在问题
    validate-on-migrate: true
    # 生产环境一定要关闭
    clean-disabled: true
    # 校验路径下是否存在 SQL 文件
    check-location: false
    # 最开始已经存在表结构，且不存在 flyway_schema_history 表时，需要设置为 true
    baseline-on-migrate: true
    # 基础版本 0
    baseline-version: 0

#日志打印
mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    # 关闭二级缓存
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#########################################################################################################
########################################## 分布式文件系统fastdfs配置 #############################################
######################################################################################
#fdfs:
#  # socket连接超时时长
#  soTimeout: 1500
#  # 连接tracker服务器超时时长
#  connectTimeout: 600
#  pool:
#    # 从池中借出的对象的最大数目
#    max-total: 153
#    # 获取连接时的最大等待毫秒数100
#    max-wait-millis: 102
#  # 缩略图生成参数，可选
#  thumbImage:
#    width: 150
#    height: 150
#  # 跟踪服务器tracker_server请求地址,支持多个，这里只有一个，如果有多个在下方加- x.x.x.x:port
#  trackerList:
#    - 192.168.35.12:22122
#  #
#  # 存储服务器storage_server访问地址
#  web-server-url: http://192.168.35.12:8888/


# 信息安全
security:
  csrf:
    enable: false   # false表示关闭，true为打开，默认打开
    excludes:
      - /img		#忽略检查的url
      - /js

########################## 动态修改输出日志等级功能 ##################################
log:
  update-level:
    enable: true   # 默认关闭，true表示开启此功能

server :
  port : 8080



