####################################################################################
###################################DataSource Config################################
####################################################################################
spring:
  datasource:
    #    schema:
    #      - classpath:/db/schema-mysql.sql
    #    data:
    #      - classpath:/db/data-mysql.sql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://216.240.130.167:3306/sakura?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
#########################################################################################################
##########################################spring boot rabbitmq #############################################
#########################################################################################################
  rabbitmq:
    host: 216.240.130.167
    port: 5672
    virtual-host: /sakura
    username: sakura
    password: sakura
    listener:
      simple:
        acknowledge-mode: manual #开启手动Ack。消息默认设置为自动ack，这种情况下，MQ只要确认消息发送成功，无须等待应答就会丢弃消息
        prefetch: 2

#########################################################################################################
##########################################spring boot redis #############################################
######################################################################################
  redis:
    database: 0           # Redis数据库索引（默认为0）
    host: 216.240.130.167  # Redis服务器地址
    port: 6379            # Redis服务器连接端口
    password:             #Redis服务器连接密码（默认为空）
    timeout: 5000ms            # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-idle: 8         # 连接池中的最大空闲连接
        min-idle: 1         # 连接池中的最小空闲连接
        max-active: 8       # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms        # 连接池最大阻塞等待时间（使用负值表示没有限制）
  profiles:
    active: dev

#########################################################################################################
########################################## 文件上传 #############################################
######################################################################################
  servlet:
    multipart:
      max-file-size: 100MB # 最大支持文件大小
      max-request-size: 100MB # 最大支持请求大小

#########################################################################################################
########################################## flyway #############################################
######################################################################################
  flyway:
    enabled: true
    # 迁移前校验 SQL 文件是否存在问题
    validate-on-migrate: true
    # 生产环境一定要关闭
    clean-disabled: true
    # 校验路径下是否存在 SQL 文件
    check-location: false
    # 最开始已经存在表结构，且不存在 flyway_schema_history 表时，需要设置为 true
    baseline-on-migrate: true
    # 基础版本 0
    baseline-version: 0

#日志打印
mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    # 关闭二级缓存
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#########################################################################################################
########################################## 分布式文件系统fastdfs配置 #############################################
######################################################################################
#fdfs:
#  # socket连接超时时长
#  soTimeout: 1500
#  # 连接tracker服务器超时时长
#  connectTimeout: 600
#  pool:
#    # 从池中借出的对象的最大数目
#    max-total: 153
#    # 获取连接时的最大等待毫秒数100
#    max-wait-millis: 102
#  # 缩略图生成参数，可选
#  thumbImage:
#    width: 150
#    height: 150
#  # 跟踪服务器tracker_server请求地址,支持多个，这里只有一个，如果有多个在下方加- x.x.x.x:port
#  trackerList:
#    - 192.168.35.12:22122
#  #
#  # 存储服务器storage_server访问地址
#  web-server-url: http://192.168.35.12:8888/


# 信息安全
security:
  csrf:
    enable: true   # false表示关闭，true为打开，默认打开
    excludes:
      - /img		#忽略检查的url
      - /js



########################## 动态修改输出日志等级功能 ##################################
log:
  update-level:
    enable: true   # 默认关闭，true表示开启此功能

server :
  port : 8080



