server :
  port : 8888
  tomcat:
    uri-encoding: UTF-8

spring:
  cloud:
    gateway:
      # discovery:
      #   locator:
      #     lower-case-service-id: true #使用小写服务名，默认是大写
      #     enabled: false  #开启从注册中心动态创建路由的功能，利用微服务名进行路由，开启此配置后，可以不需要配置routes
      routes:
        #路由的ID
        - id: web-service
          #匹配后路由地址
          uri: lb://web-service
          order: 1
          predicates: # 断言，路径相匹配的进行路由
            - Path=/web/**
          filters:
            # - PrefixPath=/sakura
            - StripPrefix=1