server :
  port : 8888
  tomcat:
    uri-encoding: UTF-8

knife4j:
  # 聚合swagger文档
  gateway:
    enabled: true
    # 指定手动配置的模式(默认为该模式)
    strategy: manual
    routes:
      - name: 用户服务
        # 真实子服务访问url地址-提供OpenAPI的文档
        url: /web-service-demo/v2/api-docs?group=default
        service-name: web-service-demo
        # 路由前缀
        # 兼容OpenAPI3规范在聚合时丢失contextPath属性的异常情况，由开发者自己配置contextPath,Knife4j的前端Ui做兼容处理,与url属性独立不冲突，仅OpenAPI3规范聚合需要，OpenAPI2规范不需要设置此属性,默认为(apiPathPrefix)
        #context-path: /
        order: 2

spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true #使用小写服务名，默认是大写
          enabled: false  #开启从注册中心动态创建路由的功能，利用微服务名进行路由，开启此配置后，可以不需要配置routes
      routes:
        #路由的ID
        - id: web-service-demo
          #匹配后路由地址
          uri: lb://web-service-demo
          order: 1
          predicates: # 断言，路径相匹配的进行路由
            - Path=/web-service-demo/**
          filters:
            # - PrefixPath=/sakura
            - StripPrefix=1
        #minio路由的ID，访问minio的附件都走网关
        - id: minio
          #minio的ip
          uri: http://120.0.0.1:9000
          predicates: # 断言，路径相匹配的进行路由
            - Path=/minio/**
          filters:
            # - PrefixPath=/sakura
            - StripPrefix=1
        - id: uid-generator-demo
          uri: lb://uid-generator-demo
          order: 1
          predicates:
            - Path=/uid-generator-demo/**
          filters:
            - StripPrefix=1
        - id: dynamic-cron-demo
          uri: lb://dynamic-cron-demo
          order: 1
          predicates:
            - Path=/dynamic-cron-demo/**
          filters:
            - StripPrefix=1
        - id: es-demo
          uri: lb://es-demo
          order: 1
          predicates:
            - Path=/es-demo/**
          filters:
            - StripPrefix=1
        - id: fastdfs-demo
          uri: lb://fastdfs-demo
          order: 1
          predicates:
            - Path=/fastdfs-demo/**
          filters:
            - StripPrefix=1
        - id: jpa-demo
          uri: lb://jpa-demo
          order: 1
          predicates:
            - Path=/jpa-demo/**
          filters:
            - StripPrefix=1
        - id: minio-demo
          uri: lb://minio-demo
          order: 1
          predicates:
            - Path=/minio-demo/**
          filters:
            - StripPrefix=1
        - id: rabbitmq-demo
          uri: lb://rabbitmq-demo
          order: 1
          predicates:
            - Path=/rabbitmq-demo/**
          filters:
            - StripPrefix=1
        - id: redis-demo
          uri: lb://redis-demo
          order: 1
          predicates:
            - Path=/redis-demo/**
          filters:
            - StripPrefix=1
        - id: web-socket-demo
          uri: lb://web-socket-demo
          order: 1
          predicates:
            - Path=/web-socket-demo/**
          filters:
            - StripPrefix=1
        - id: netty-service-demo
          uri: lb://netty-service-demo
          order: 1
          predicates:
            - Path=/netty-service-demo/**
          filters:
            - StripPrefix=1