server :
  port : 8080
  tomcat:
    uri-encoding: UTF-8

# 为 jasypt 配置解密秘钥
jasypt:
  encryptor:
    password: sinvie2022
    # algorithm: PBEWithMD5AndDES

knife4j:
  enable: true
  openapi:
    title: sakura-boot-demo
    description: "sakura-boot-demo接口文档"
    email: 13142188325@163.com
    concat: 木一番
    version: v1.1
    group:
      test1:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.sakura.cloud
####################################################################################
###################################DataSource Config################################
####################################################################################
spring:
  ############# 达梦方言配置 ##########
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.DmDialect
#    database-platform: org.hibernate.dialect.DmDialect
  datasource:

    ############# 达梦 ##########
    ##    driver-class-name: dm.jdbc.driver.DmDriver
#    url: jdbc:dm://192.168.1.184:5236/
#    username: sakura
#    password: sakura

    ############# 金仓 ##########
#    driver-class-name: com.kingbase8.Driver
#    url: jdbc:kingbase8://192.168.1.184:54321/sioc_3_0?useUnicode=true&characterEncoding=UTF-8

    ############# MYSQL ##########
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sakura?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
#    username: ENC(YebLZShoLHbiTberWNUwnw==)
#    password: ENC(mhtmWKH23/brnPS1EwEo3Q==)

#########################################################################################################
########################################## flyway #############################################
######################################################################################
  flyway:
    # flyway官方不支持达梦，需要关闭
    enabled: false
    # 迁移前校验 SQL 文件是否存在问题
    validate-on-migrate: true
    # 生产环境一定要关闭
    clean-disabled: true
    # 校验路径下是否存在 SQL 文件
    check-location: false
    # 最开始已经存在表结构，且不存在 flyway_schema_history 表时，需要设置为 true
    baseline-on-migrate: true
    # 基础版本 0
    baseline-version: 0

#日志打印
mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    # 关闭二级缓存
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 信息安全
security:
  csrf:
    enabled: true   # false表示关闭，true为打开，默认打开
    excludes:
      - /img		#忽略检查的url
      - /js

########################## 动态修改输出日志等级功能 ##################################
log:
  update-level:
    enabled: true   # 默认关闭，true表示开启此功能




