server :
  port : 8087
  tomcat:
    uri-encoding: UTF-8

####################################################################################
###################################DataSource Config################################
####################################################################################
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sakura?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: admin

#########################################################################################################
########################################## powerjob #############################################
######################################################################################
powerjob:
  worker:
    # akka 工作端口，可选，默认 27777
    akka-port: 27777
    # 接入应用名称，用于分组隔离，推荐填写 本 Java 项目名称
    app-name: powerjob
    # 调度服务器地址，IP:Port 或 域名，多值逗号分隔
    server-address: 192.168.3.13:7700
    # 持久化方式，可选，默认 disk
    store-strategy: disk
    # 任务返回结果信息的最大长度，超过这个长度的信息会被截断，默认值 8192
    max-result-length: 4096
    # 单个任务追加的工作流上下文最大长度，超过这个长度的会被直接丢弃，默认值 8192
    max-appended-wf-context-length: 4096

# 需要关闭sql盲注，cron表达式中有*，会导致接口不通过
security:
  sql:
    enabled: false
