server :
  port : 9100
  tomcat:
    uri-encoding: UTF-8

####################################################################################
###################################DataSource Config################################
####################################################################################
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sakura?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: admin
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    password:

#日志打印
mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    # 关闭二级缓存
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 信息安全
security:
  csrf:
    enabled: true   # false表示关闭，true为打开，默认打开
    excludes:
      - /img		#忽略检查的url
      - /js
  sql:
    enabled: true   # false表示关闭，true为打开，默认打开
    excludes:
      - /img        #忽略检查的url
      - /js

########################## 动态修改输出日志等级功能 ##################################
log:
  update-level:
    enabled: true   # 默认关闭，true表示开启此功能


