server :
  port : 8085
  tomcat:
    uri-encoding: UTF-8

########################################################################################################
##########################################spring boot redis #############################################
######################################################################################
spring:
  redis:
    database: 0           # Redis数据库索引（默认为0）
    host: 192.168.3.13  # Redis服务器地址
    port: 6379            # Redis服务器连接端口
    password:             #Redis服务器连接密码（默认为空）
    timeout: 5000ms            # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-idle: 8         # 连接池中的最大空闲连接
        min-idle: 1         # 连接池中的最小空闲连接
        max-active: 8       # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms        # 连接池最大阻塞等待时间（使用负值表示没有限制）
  profiles:
    active: dev
